# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        label: indikator.paste::lang.form.category
        modelClass: Indikator\SellProducts\Models\Category
        conditions: category in (:filtered)
        nameFrom: name

    sale_price:
        label: indikator.sellproducts::lang.form.sale
        type: checkbox
        conditions: sale_price != ''

    status_active:
        label: indikator.sellproducts::lang.form.status_active
        type: checkbox
        conditions: status = 1

    status_inactive:
        label: indikator.sellproducts::lang.form.status_inactive
        type: checkbox
        conditions: status = 2

    created_date:
        label: indikator.sellproducts::lang.list.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.sellproducts::lang.list.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
