# ===================================
#  List Behavior Config
# ===================================

title: indikator.sellproducts::lang.menu.products
list: ~/plugins/indikator/sellproducts/models/products/columns.yaml

modelClass: Indikator\SellProducts\Models\Products
recordUrl: indikator/sellproducts/products/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: name
    direction: asc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
