# ===================================
#  Reorder Behavior Config
# ===================================

title: indikator.sellproducts::lang.button.reorder

nameFrom: name

modelClass: Indikator\SellProducts\Models\Category

toolbar:
    buttons: reorder_toolbar
